# evaluate.py
import argparse
import json
import sys
from dataclasses import asdict
from pathlib import Path

from tonofdevelopervoice.evaluate.embedder import MiniLMEmbedder
from tonofdevelopervoice.evaluate.perplexity_model import GPT2Perplexity
from tonofdevelopervoice.evaluate.reference_scorer import BERTScoreScorer
from tonofdevelopervoice.evaluate.report import EvalExample, build_report
from tonofdevelopervoice.evaluate.style_classifier import StyleClassifier


def load_jsonl(path: Path) -> list[dict[str, str]]:
    records = []
    with path.open(encoding="utf-8") as f:
        for line in f:
            records.append(json.loads(line))
    return records


def fit_style_classifier(train_file: Path) -> tuple[StyleClassifier, float]:
    records = load_jsonl(train_file)
    authentic = [r["output"] for r in records]
    synthetic = [r["input"] for r in records]
    classifier = StyleClassifier()
    result = classifier.fit(authentic, synthetic)
    return classifier, result.held_out_accuracy


def load_examples(eval_file: Path) -> list[EvalExample]:
    records = load_jsonl(eval_file)
    return [
        EvalExample(source=r["source"], model_output=r["model_output"], reference=r["reference"])
        for r in records
    ]


def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Score model outputs (source/model_output/reference triples, generated by "
            "running the real trained model on the host) against the automated style, "
            "content and fluency metrics from docs/research/evaluation.md."
        )
    )
    parser.add_argument(
        "--eval-file", required=True, type=Path, help="JSONL of {source, model_output, reference}"
    )
    parser.add_argument(
        "--train-file", required=True, type=Path, help="JSONL of {input, output} for the classifier"
    )
    parser.add_argument("--out", required=True, type=Path)
    args = parser.parse_args()

    classifier, accuracy = fit_style_classifier(args.train_file)
    examples = load_examples(args.eval_file)

    report = build_report(
        examples,
        embedder=MiniLMEmbedder(),
        scorer=BERTScoreScorer(),
        classifier=classifier,
        style_classifier_accuracy=accuracy,
        perplexity_model=GPT2Perplexity(),
        judge=None,
    )

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(asdict(report), indent=2) + "\n", encoding="utf-8")
    print(f"wrote report to {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
